### PR TITLE
Update README.md - command line options order

### PR DESCRIPTION
**Pull request by mattseymour**
This commit reorders the commandline options alphabetically so, they are easier to scroll, read, and find.
It also groups aws specific commands into a specific section.

Note: The contents of the readme and the commandline options have not changed.

### CODE REVIEW

**Comment by ferronrsmith** [comment]
https://github.com/elasticsearch-dump/elasticsearch-dump/blob/master/lib/help.txt should also be updated

**Comment by ferronrsmith** [comment]
input/input-index/output/output-index. These are the primary transport commands. While I do like the alphabetical, i always want these at the top, due to importance.

maybe a section at the top for those commands. **Core Transport Commands** etc

**Comment by mattseymour** [comment]
Agree with the comments you made here. This was an oversight on my part. I will make the changes and update.

**Comment by ferronrsmith** [comment]
Thanks for your contribution

**Pull request merged**
