### PR TITLE
Update README.md to add bulkAction argument

### PR DESCRIPTION
**Pull request by TheRealMattLear**
Documentation for bulkAction missing.
Changing bulkAction to create was required to output into a data streams

### CODE REVIEW

**Comment by ferronrsmith** [comment]
https://github.com/elasticsearch-dump/elasticsearch-dump/blob/master/lib/help.txt should be update also

**Comment by TheRealMattLear** [comment]
Updated :)

**Comment by ferronrsmith** [comment]
`Action to send to the Bulk API` sounds a bit misleading or not informative. What action ?

`bulkAction` - sets the operation type to be used when preparing the request body to be sent to elastic search. 
For more info - https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html
(default: index, options: [index, update, delete, create)

**Comment by ferronrsmith** [comment]
Thanks for your contribution

**Pull request merged**
